apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx-route
  namespace: {{ .Values.namespace }}
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: nginx-service
  port:
    targetPort: {{ .Values.service.port }}
  tls:
    termination: edge
  wildcardPolicy: None
